FROM python:3.12.8 

RUN apt-get update && apt-get install -y \
    curl \ 
    && rm -rf /var/lib/apt/lists/* 

RUN pip install pandas sqlalchemy psycopg2 pyarrow

WORKDIR /app 
COPY ingest_data.py ingest_data.py

ENTRYPOINT [ "python", "ingest_data.py" ]